apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
            - name: TEST_123
              value: "Test Fabric8 Plugin Conventions"
