apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "definition", "namespace": "",
      "kind": "DeploymentConfig"}]'
  creationTimestamp: 2017-02-01T23:09:54Z
  labels:
    name: definition-pipeline
  name: definition-pipeline
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'build'
        openshiftBuild(buildConfig: 'definition', showBuildLogs: 'true')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'definition')
        stage 'test'
        sh 'curl http://gateway-fis-bby-ca-hysterix.cloudapps.rhneolabs.com/api/definition/camel | grep -i "genus"'
        stage 'tag image'
        openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'definition', destTag: 'next-release', destinationAuthToken: '', destinationNamespace: '', namespace: '', srcStream: 'definition', srcTag: 'latest', verbose: 'false'
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
