apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "product-catalog", "namespace": "",
      "kind": "DeploymentConfig"}]'
  labels:
    name: product-catalog-pipeline
  name: product-catalog-pipeline
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'build'
        openshiftBuild(buildConfig: 'product-catalog-s2i', showBuildLogs: 'true')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'product-catalog')
        stage 'test'
        sh 'curl http://product-catalog-product-catalog-demo01.cloudapps.keyvan.com | grep -i "Admin - Product List"'
        stage 'tag image'
        openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'product-catalog', destTag: 'next-release', destinationAuthToken: '', destinationNamespace: '', namespace: '', srcStream: 'product-catalog', srcTag: 'latest', verbose: 'false'
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
