apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "definition", "namespace": "",
      "kind": "DeploymentConfig"}]'
  labels:
    name: definition-promote
  name: definition-promote
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'promote release'
        openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'definition', destTag: 'current-release', destinationAuthToken: '', destinationNamespace: '', namespace: '', srcStream: 'definition', srcTag: 'next-release', verbose: 'false'
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'definition')
        stage 'smoke test current release'
        sh 'curl http://gateway-fis-bby-ca-hysterix.cloudapps.rhneolabs.com/api/definition/camel | grep -i "genus"'
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
type: Generic
